# Generated by Django 5.0.6 on 2024-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                help_text="Введите цену", verbose_name="Цена за покупку"
            ),
        ),
    ]
