# Generated by Django 5.0.6 on 2024-07-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["manufactured_at"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created_at",
            new_name="manufactured_at",
        ),
    ]
