# Generated by Django 5.1 on 2024-08-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    ("can_cancel_publication", "Can cancel publication of product"),
                    ("can_change_description", "Can change description of product"),
                    ("can_change_product_category", "Can change product category"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
