# Generated by Django 5.1 on 2024-08-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать продукт",
                verbose_name="Опубликовано",
            ),
        ),
    ]
